version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: Mongo2Go
    versions:
    - 3.0.0
    - 3.1.0
    - 3.1.1
  - dependency-name: Akka.Persistence.TCK
    versions:
    - 1.4.17
  - dependency-name: akka.streams
    versions:
    - 1.4.17
  - dependency-name: Akka.Persistence.Query
    versions:
    - 1.4.17
  - dependency-name: FluentAssertions
    versions:
    - 5.10.3
